/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;

/**
 *
 * @author 666
 */
public class Cliente extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Cliente
     */
    
    String usuario,grupo;
    Socket client;
    ObjectOutputStream out;
    ObjectInputStream in;
    Thread hilo;
    DefaultListModel modelo;
    
    
    public Cliente() {
        initComponents();
        modelo = new DefaultListModel();
        JTextField usuario = new JTextField(20);
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(1, 2));
        panel.add(new JLabel("Nombre del usuario:"));
        panel.add(usuario);
        btn_Salir.setEnabled(false);
        int result = JOptionPane.showConfirmDialog(this, panel, "Unirse", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            this.usuario=usuario.getText();
            this.grupo="";
            lbl_Usuario.setText("G:No unido"+this.grupo+" - U:"+this.usuario);
            try {
                client=new Socket("localhost", 5000);
                out=new ObjectOutputStream(client.getOutputStream());
                in=new ObjectInputStream(client.getInputStream());
                LocalDateTime local=LocalDateTime.now();
                String fecha=local.getDayOfWeek()+" "+local.getHour()+":"+local.getMinute();
                DataCliente dCliente = new DataCliente(this.usuario, "Conex", "Conectad@ "+fecha, grupo);
                out.writeObject(dCliente);
                hilo=new Thread(this);
                hilo.start();            
            } catch (IOException ex) {
                Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            System.exit(0);
        }
    }
    
    @Override
    public void run() {
        try {
            while (true) {
                Object dCliente = in.readObject();
                if(dCliente instanceof DataCliente){
                    actions((DataCliente)dCliente);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void actions(DataCliente data){
        String comand = data.getComando();
        String chat;
        switch(comand){
            case "newGroup":
                chat = txt_Chat.getText();
                txt_Chat.setText(data.getUsuario()+": Nuevo grupo creado - "+data.getGrupo()+"\n"+chat);
                modelo.addElement(data.getGrupo());
                break;
            case "joinGroup":
                chat = txt_Chat.getText();
                txt_Chat.setText(data.getUsuario()+": "+data.getMensaje()+" "+data.getGrupo()+"\n"+chat);
                break;
            case "leaveGroup":
                chat = txt_Chat.getText();
                txt_Chat.setText(data.getUsuario()+": "+data.getMensaje()+" "+data.getGrupo()+"\n"+chat);
                break;
            case "All":
                chat = txt_Chat.getText();
                txt_Chat.setText(data.getUsuario()+":"+data.getMensaje()+"\n"+chat);
                break;
            default:
                break;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Enviar = new javax.swing.JTextField();
        btn_Enviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Chat = new javax.swing.JTextArea();
        btn_Crear = new javax.swing.JButton();
        btn_Unirse = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        lbl_Usuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Enviar.setText("Enviar");
        btn_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EnviarActionPerformed(evt);
            }
        });

        txt_Chat.setColumns(20);
        txt_Chat.setRows(5);
        jScrollPane1.setViewportView(txt_Chat);

        btn_Crear.setText("Crear grupo");
        btn_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearActionPerformed(evt);
            }
        });

        btn_Unirse.setText("Unirse a grupo");
        btn_Unirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UnirseActionPerformed(evt);
            }
        });

        btn_Salir.setText("Salir de grupo");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        lbl_Usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Usuario.setText("Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addComponent(txt_Enviar, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lbl_Usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btn_Enviar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btn_Crear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Unirse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Salir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Crear)
                    .addComponent(btn_Unirse)
                    .addComponent(btn_Salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Usuario)
                .addGap(12, 12, 12)
                .addComponent(txt_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Enviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EnviarActionPerformed
        if(!grupo.isEmpty()){
            String msj=txt_Enviar.getText();
            if(!msj.equals("")){
                try {
                    DataCliente dCliente = new DataCliente(usuario, "All", msj, grupo);
                    out.writeObject(dCliente);
                    txt_Enviar.setText("");
                } catch (IOException ex) {
                    Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "No se ha unido a un grupo aun, cree uno nuevo o unase a uno","Sin grupo aun",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_EnviarActionPerformed

    private void btn_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearActionPerformed
        JTextField nombreGrupo = new JTextField(20);
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(1, 2));
        panel.add(new JLabel("Nombre del grupo:"));
        panel.add(nombreGrupo);
        int result = JOptionPane.showConfirmDialog(this, panel, "Nuevo Grupo", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            grupo = nombreGrupo.getText();
            DataCliente dCliente = new DataCliente(this.usuario, "newGroup", "Nuevo grupo",grupo);
            try {
                modelo.addElement(grupo);
                out.writeObject(dCliente);
                btn_Salir.setEnabled(true);
                lbl_Usuario.setText("G:"+this.grupo+" - U:"+this.usuario);
            } catch (IOException ex) {
                Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_CrearActionPerformed

    private void btn_UnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UnirseActionPerformed
        JList lstGrupo = new JList();
        lstGrupo.setModel(modelo);
        lstGrupo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        JScrollPane scroll = new JScrollPane();
        scroll.setBounds(20, 120,220, 80);
        scroll.setViewportView(lstGrupo);
        JPanel panel = new JPanel();
        JLabel lblGrupo = new JLabel("Seleccione un grupo");
        lblGrupo.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblGrupo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.setLayout(new BorderLayout());
        panel.add(lblGrupo,BorderLayout.NORTH);
        panel.add(lstGrupo,BorderLayout.CENTER);
        int result = JOptionPane.showConfirmDialog(this, panel, "Unirse a grupo", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            if(!modelo.isEmpty()){
                grupo = (String) modelo.get(lstGrupo.getSelectedIndex());
                DataCliente dCliente = new DataCliente(this.usuario, "joinGroup", "Unirse a grupo",grupo);
                try {
                    out.writeObject(dCliente);
                    btn_Salir.setEnabled(true);
                    lbl_Usuario.setText("G:"+this.grupo+" - U:"+this.usuario);
                } catch (IOException ex) {
                    Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Nombre vacio, comience de nuevo","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_UnirseActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "¿Está seguro de abandonar el grupo?", "Salir del grupo", JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            DataCliente dCliente = new DataCliente(this.usuario, "leaveGroup", "Abandonar grupo",grupo);
            try {
                out.writeObject(dCliente);
                btn_Salir.setEnabled(false);
                lbl_Usuario.setText("G:No unido - U:"+this.usuario);
                grupo="";
            } catch (IOException ex) {
                Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_SalirActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Crear;
    private javax.swing.JButton btn_Enviar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_Unirse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Usuario;
    private javax.swing.JTextArea txt_Chat;
    private javax.swing.JTextField txt_Enviar;
    // End of variables declaration//GEN-END:variables

}
